;             
CREATE USER IF NOT EXISTS "SA" SALT 'bf9f3f591b9ada00' HASH 'a46f2793ba2e111346174d4e31ef0ef539cad89ff39b3a71039e288f941d876d' ADMIN;         
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 784; 
CREATE CACHED TABLE "PUBLIC"."CARRINHO"(
    "GUID_CARRINHO" INTEGER NOT NULL,
    "PRECO_BEAT" VARCHAR(255),
    "BEAT_GUID_BEAT" INTEGER,
    "USUARIO_GUID_USUARIO" INTEGER
);        
ALTER TABLE "PUBLIC"."CARRINHO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2E" PRIMARY KEY("GUID_CARRINHO");         
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.CARRINHO;               
INSERT INTO "PUBLIC"."CARRINHO" VALUES
(642, '15', 164, 1),
(643, '20', 169, 1),
(644, '20', 166, 1),
(645, '30', 163, 1),
(646, '15', 167, 1),
(675, '20', 164, 674),
(676, '15', 169, 674),
(678, '50', 677, 1),
(679, '20', 168, 1),
(711, '15', 170, 1);        
CREATE CACHED TABLE "PUBLIC"."DESCONTOS"(
    "GUID_DESCONTO" INTEGER NOT NULL,
    "NOME" VARCHAR(255),
    "PORCENTAGEM" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."DESCONTOS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("GUID_DESCONTO");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DESCONTOS;               
CREATE CACHED TABLE "PUBLIC"."ORDER_PRODUCT"(
    "QUANTITY" INTEGER NOT NULL,
    "GUID_BEAT" INTEGER NOT NULL,
    "GUID_PEDIDO" BIGINT NOT NULL
);     
ALTER TABLE "PUBLIC"."ORDER_PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("GUID_BEAT", "GUID_PEDIDO");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ORDER_PRODUCT;           
CREATE CACHED TABLE "PUBLIC"."PEDIDO"(
    "GUID_PEDIDO" BIGINT NOT NULL,
    "DATA" DATE,
    "STATUS" VARCHAR(255)
);   
ALTER TABLE "PUBLIC"."PEDIDO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("GUID_PEDIDO");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PEDIDO;  
CREATE CACHED TABLE "PUBLIC"."FAVORITOS"(
    "GUID_CARRINHO" INTEGER NOT NULL,
    "BEAT_GUID_BEAT" INTEGER,
    "USUARIO_GUID_USUARIO" INTEGER
);       
ALTER TABLE "PUBLIC"."FAVORITOS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3B" PRIMARY KEY("GUID_CARRINHO");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FAVORITOS;               
CREATE CACHED TABLE "PUBLIC"."USUARIO"(
    "GUID_USUARIO" INTEGER NOT NULL,
    "EMAIL" VARCHAR(255),
    "LOGIN" VARCHAR(255),
    "SENHA" VARCHAR(255),
    "ROLE" VARCHAR(255),
    "CARRINHO" BINARY(255),
    "IMAGEM" VARCHAR(255),
    "OTP" INTEGER,
    "CPF" VARCHAR(255),
    "NOME" VARCHAR(255),
    "SOBRE" VARCHAR(255),
    "SOBRENOME" VARCHAR(255)
);         
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("GUID_USUARIO");            
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO;
INSERT INTO "PUBLIC"."USUARIO" VALUES
(1, 'luissouzasanto@gmail.com', 'luigi', '$2a$12$8GyStcbXtEN/FtJ/dRuLCeK5SrCtWepB3aPr.8FpgT.mbrVw/FXcG', 'admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(161, 'email@email.com', 'user5', '$2a$10$4Jsfpb2J0SuUOexwpCyEieLsBYVrHrRrCdeV8qde6Rr9py1NmlnwG', 'user', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(194, 'email@email.com', 'cleverson', '$2a$10$hnBMBBOJxjK64RvZ6vIz1.JfpNfBtTefV.Iz2ISAa55RR.TLYF2vK', 'user', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(258, 'email@email.com', 'henrique', '$2a$10$HrLWRMt11nT8DbASnmtDk.i92Rsjl2i8XL3OUfwwH.ukpEk.LeQEy', 'user', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(290, 'user@email.com', 'user', '$2a$10$mi./bWaT/qfLRaYBCq2tyeALO2vpbw6wpINCJD2QDKOVZx5LpdazK', 'user', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(322, 'user1@email.com', 'user1', '$2a$10$AfbAv6Er7LpktrsJvyJiueMEJBmvi/6p504ef.TH4cZKuadL/Q9bK', 'user', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(354, 'cleverson@email.com', 'cleverson', '$2a$10$OR20aGRSH1qaJwkzBHgqiObXne0IelxxZ56HOjY1S3FRHMohX7spq', 'user', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(355, 'vini@email.com', 'vini', '$2a$10$QEJbV1fM3UOlpkKCOxcuoeYcd9W0VBZHdBSQwpxKcTSIfzQUSuCwe', 'user', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(674, 'user8@email.com', 'user8', '$2a$10$fl8c0cndibAymgWUJUfSYOjrPKWUTYuV/d7fhdQiIy1MgisS3OWeW', 'user', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(783, 'joaopx@yahoo.com.br', 'joaoxavi', '$2a$10$/lLwKpCA54hdbrr.U3eLXes5a2xrveP8XOBb4ajM6q/ESkp3hjJZ6', 'user', NULL, NULL, 95668, NULL, NULL, NULL, NULL);  
CREATE CACHED TABLE "PUBLIC"."BEATS"(
    "GUID_BEAT" INTEGER NOT NULL,
    "BPM" VARCHAR(255),
    "DATA_LANCAMENTO" TIMESTAMP,
    "IMAGEM" VARCHAR(255),
    "NOTA" VARCHAR(255),
    "PRECO_BASIC" VARCHAR(255),
    "PRECO_PREMIUM" VARCHAR(255),
    "PRECO_UNLIMITED" VARCHAR(255),
    "STEMS" VARCHAR(255),
    "TAGS" VARCHAR(255),
    "TITULO" VARCHAR(255),
    "WAV_TAGGED" VARCHAR(255),
    "WAV_UNTAGGED" VARCHAR(255),
    "SELECTED" INTEGER,
    "USUARIO_GUID_USUARIO" INTEGER,
    "DISCOUNT" FLOAT
); 
ALTER TABLE "PUBLIC"."BEATS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("GUID_BEAT"); 
-- 13 +/- SELECT COUNT(*) FROM PUBLIC.BEATS;  
INSERT INTO "PUBLIC"."BEATS" VALUES
(163, '85', TIMESTAMP '2022-11-24 11:57:00', 'beat2.png', 'A#m', '15', '20', '30', 'stems test.rar', NULL, 'Aura | Vhulto Type Beat', 'mix2.wav', 'mix2.wav', NULL, NULL, NULL),
(164, '120', TIMESTAMP '2022-11-24 11:59:00', 'beat1.png', 'Am', '15', '20', '30', 'stems test.rar', NULL, 'Spotlight | Lil Peep x Smokeasac Type Beat', 'mix2.wav', 'mix2.wav', NULL, NULL, NULL),
(165, '155', TIMESTAMP '2022-11-24 12:00:00', 'beat3.png', 'G#m', '15', '20', '30', 'stems test.rar', NULL, 'June | Nick Mira x Juice Wrld Type Beat', 'mix2.wav', 'mix2.wav', NULL, NULL, NULL),
(166, '140', TIMESTAMP '2022-11-24 12:14:00', 'beat4.png', 'Dm', '15', '20', '30', 'stems test.rar', NULL, '1984 | Glaive x Ericdoa Type Beat', 'mix2.wav', 'mix2.wav', NULL, NULL, NULL),
(167, '130', TIMESTAMP '2022-11-24 12:15:00', 'beat5.png', 'Bm', '15', '20', '30', 'stems test.rar', NULL, 'Road | Plugg Type Beat', 'mix2.wav', 'mix2.wav', NULL, NULL, NULL),
(168, '160', TIMESTAMP '2022-11-24 12:16:00', 'beat6.png', 'Cm', '15', '20', '30', 'stems test.rar', NULL, 'Lucid | Juice Wrld x Nick Mira Type Beat', 'mix2.wav', 'mix2.wav', NULL, NULL, NULL),
(169, '105', TIMESTAMP '2022-11-24 12:17:00', 'beat7.png', 'Em', '15', '20', '30', 'stems test.rar', NULL, 'Antes | Ferno x Matue Type Beat', 'mix2.wav', 'mix2.wav', NULL, NULL, NULL),
(170, '120', TIMESTAMP '2022-11-24 12:18:00', 'beat8.png', 'F#m', '15', '20', '30', 'stems test.rar', NULL, 'Kyushu | Japa Type Beat', 'mix2.wav', 'mix2.wav', NULL, NULL, NULL),
(195, '155', TIMESTAMP '2022-11-25 16:45:00', 'beat12.png', 'C#m', '15', '20', '30', 'stems test.rar', NULL, 'Titulo tesdte', 'mix2.wav', 'mix2.wav', NULL, NULL, NULL),
(226, '150', TIMESTAMP '2022-12-23 23:13:00', 'beat11.png', 'Am', '27', '35', '50', 'stems test.rar', NULL, 'beat18', 'mix2.wav', 'mix2 (1).wav', NULL, NULL, NULL),
(356, '130', TIMESTAMP '2023-05-20 17:54:00', 'beat6.png', 'C#', '15', '20', '30', 'empty.rar', NULL, 'TESTE22', 'mix2 (4).wav', 'mix2 (4).wav', NULL, NULL, NULL),
(677, '155', NULL, 'palm1.gif', 'C major', '25', '50', '80', 'FLARE-1818-WIN.rar', NULL, 'TituloTESTE', '80s_2.wav', '80s_2.wav', NULL, NULL, NULL),
(780, '123', NULL, 'roblse.png', 'c#m', '12', '12', '12', '1.jpg', NULL, 'Teste', '1.jpg', 'urls_non_labeled.csv', NULL, 1, NULL);     
ALTER TABLE "PUBLIC"."ORDER_PRODUCT" ADD CONSTRAINT "PUBLIC"."FKJ1AKJWWG0JYKFJPVXJ1TUJWCV" FOREIGN KEY("GUID_BEAT") REFERENCES "PUBLIC"."BEATS"("GUID_BEAT") NOCHECK;         
ALTER TABLE "PUBLIC"."ORDER_PRODUCT" ADD CONSTRAINT "PUBLIC"."FKIHC3K5TA9F9H0UD4C18D0WPAK" FOREIGN KEY("GUID_PEDIDO") REFERENCES "PUBLIC"."PEDIDO"("GUID_PEDIDO") NOCHECK;    
ALTER TABLE "PUBLIC"."FAVORITOS" ADD CONSTRAINT "PUBLIC"."FK46JS0DEC2761CYRC7MORLRHMN" FOREIGN KEY("BEAT_GUID_BEAT") REFERENCES "PUBLIC"."BEATS"("GUID_BEAT") NOCHECK;        
ALTER TABLE "PUBLIC"."CARRINHO" ADD CONSTRAINT "PUBLIC"."FKIM66RQPLTVGMKPF497NBHS84T" FOREIGN KEY("USUARIO_GUID_USUARIO") REFERENCES "PUBLIC"."USUARIO"("GUID_USUARIO") NOCHECK;              
ALTER TABLE "PUBLIC"."FAVORITOS" ADD CONSTRAINT "PUBLIC"."FK1X7NIQH74YIY80EA4A2KCOT5D" FOREIGN KEY("USUARIO_GUID_USUARIO") REFERENCES "PUBLIC"."USUARIO"("GUID_USUARIO") NOCHECK;             
ALTER TABLE "PUBLIC"."CARRINHO" ADD CONSTRAINT "PUBLIC"."FKB4KNNSJNBS9H80Y226T1U21IK" FOREIGN KEY("BEAT_GUID_BEAT") REFERENCES "PUBLIC"."BEATS"("GUID_BEAT") NOCHECK;         
ALTER TABLE "PUBLIC"."BEATS" ADD CONSTRAINT "PUBLIC"."FK8VFT64MY5NL5SNIKUGG43S5H2" FOREIGN KEY("USUARIO_GUID_USUARIO") REFERENCES "PUBLIC"."USUARIO"("GUID_USUARIO") NOCHECK; 
